#pragma once

#include "../../EffectPresets.h"
#include "../../../dsp/FastDecibels.h"
#include "../../../dsp/FrDiffusionModel.h"
#include <cstdint>

namespace spatcore::effects
{

/**
    Early reflections: the discrete echoes of a room's walls, ahead of its tail.

    Four profiles (ErProfile Room, Chamber, Hall, Cathedral - Off has none),
    each a tap pattern from an image-source model of a shoebox room. The tables
    below are the output of tools/reverb/gen_er_profiles.py, which says how
    they were chosen; regenerate rather than hand-edit them. A tap is a delay
    after the predelayed direct sound and a gain. First-order taps play as
    they are; higher-order ones go through a one-pole low pass, the profile's
    "dark" frequency, because every extra bounce loses top.

    Per effects channel, every tap time is jittered by up to 4 % and every
    higher-order sign drawn, both from the channel's noise key, so thirty-two
    returns of the same room spread instead of summing into one comb.

    Size scales every time - the taps and the tail delay - the way it scales
    the reverb model's lines.

    The tail delay is where the model takes over. With reflections on, the
    model's input is the same predelayed signal that much later, so switching
    them on moves the tail back to make room for them; with them off it is not
    delayed at all.

    buildErTapSet() runs on the audio thread when a transition starts: two
    dozen hashes and multiplies, no allocation.
*/

struct ErTapSpec
{
    float ms;               // after the direct sound, at Size 1
    float gain;             // a profile's taps carry a quarter of the dry's energy
    std::uint8_t order;     // bounces: 1 plays as is, 2 and more through the dark filter
};

// Generated by tools/reverb/gen_er_profiles.py - do not edit by hand.

// Room: 6.2 x 4.8 x 3.0 m, walls 0.78, floor 0.70
inline constexpr ErTapSpec kErRoom[] =
{
    {    2.998f, 0.26024f, 1 },
    {    4.715f, 0.20208f, 1 },
    {    7.240f, 0.18793f, 1 },
    {    9.008f, 0.13137f, 2 },
    {   10.297f, 0.15658f, 1 },
    {   11.794f, 0.11291f, 2 },
    {   12.798f, 0.09644f, 2 },
    {   14.432f, 0.09965f, 2 },
    {   16.529f, 0.09114f, 2 },
    {   17.666f, 0.06794f, 3 },
    {   20.524f, 0.04924f, 3 },
    {   21.748f, 0.07516f, 2 },
    {   23.349f, 0.04993f, 3 },
    {   25.027f, 0.06770f, 2 },
    {   26.477f, 0.04540f, 3 },
    {   28.904f, 0.04727f, 3 },
};

// Chamber: 9.5 x 6.5 x 4.2 m, walls 0.88, floor 0.85
inline constexpr ErTapSpec kErChamber[] =
{
    {    2.245f, 0.22611f, 1 },
    {    7.254f, 0.17435f, 1 },
    {    9.648f, 0.15716f, 1 },
    {   11.063f, 0.13069f, 2 },
    {   12.679f, 0.13972f, 1 },
    {   13.945f, 0.11750f, 2 },
    {   14.950f, 0.12899f, 1 },
    {   16.123f, 0.10918f, 2 },
    {   17.161f, 0.10562f, 2 },
    {   18.854f, 0.10028f, 2 },
    {   20.730f, 0.09496f, 2 },
    {   22.485f, 0.07690f, 3 },
    {   24.186f, 0.07353f, 3 },
    {   26.554f, 0.07175f, 3 },
    {   28.137f, 0.07851f, 2 },
    {   31.595f, 0.07264f, 2 },
    {   34.289f, 0.05834f, 3 },
    {   37.027f, 0.05720f, 3 },
};

// Hall: 36.0 x 24.0 x 16.0 m, walls 0.82, floor 0.30
inline constexpr ErTapSpec kErHall[] =
{
    {   30.372f, 0.22154f, 1 },
    {   34.504f, 0.21042f, 1 },
    {   42.484f, 0.19182f, 1 },
    {   49.318f, 0.06524f, 1 },
    {   55.155f, 0.13793f, 2 },
    {   58.582f, 0.04884f, 2 },
    {   64.628f, 0.12631f, 2 },
    {   67.341f, 0.04512f, 2 },
    {   70.185f, 0.04403f, 2 },
    {   72.574f, 0.03539f, 3 },
    {   75.884f, 0.04200f, 2 },
    {   77.921f, 0.03388f, 3 },
    {   80.915f, 0.13454f, 1 },
    {   83.284f, 0.03250f, 3 },
    {   90.098f, 0.10297f, 2 },
    {   95.004f, 0.09944f, 2 },
    {  101.977f, 0.09481f, 2 },
    {  105.511f, 0.07595f, 3 },
    {  109.452f, 0.09030f, 2 },
    {  115.811f, 0.08679f, 2 },
};

// Cathedral: 72.0 x 28.0 x 30.0 m, walls 0.90, floor 0.45
inline constexpr ErTapSpec kErCathedral[] =
{
    {   22.047f, 0.22183f, 1 },
    {   37.099f, 0.19691f, 1 },
    {   69.671f, 0.15841f, 1 },
    {   82.636f, 0.13228f, 2 },
    {   83.674f, 0.11837f, 3 },
    {   94.193f, 0.06904f, 1 },
    {  102.720f, 0.11897f, 2 },
    {  104.331f, 0.05901f, 2 },
    {  106.264f, 0.05845f, 2 },
    {  112.039f, 0.05115f, 3 },
    {  113.417f, 0.05081f, 3 },
    {  115.428f, 0.05593f, 2 },
    {  122.282f, 0.04876f, 3 },
    {  124.597f, 0.04825f, 3 },
    {  128.023f, 0.09503f, 3 },
    {  137.352f, 0.05069f, 2 },
    {  144.358f, 0.08860f, 3 },
    {  145.693f, 0.04405f, 3 },
    {  155.379f, 0.08473f, 3 },
    {  156.991f, 0.10394f, 1 },
    {  166.197f, 0.09027f, 2 },
    {  173.337f, 0.08789f, 2 },
    {  177.085f, 0.07801f, 3 },
    {  198.577f, 0.07234f, 3 },
};

// End of generated tables.

struct ErProfileSpec
{
    const ErTapSpec* taps;
    int numTaps;
    float tailDelayMs;      // where the model's tail takes over, at Size 1
    float darkHz;           // the higher-order taps' low pass
};

/** Indexed by ErProfile. */
inline constexpr ErProfileSpec kErProfiles[] =
{
    { nullptr,       0,  0.0f, 20000.0f },          // Off
    { kErRoom,      16,  7.0f,  6000.0f },
    { kErChamber,   18, 11.0f,  8000.0f },
    { kErHall,      20, 29.0f,  5000.0f },
    { kErCathedral, 24, 68.0f,  4000.0f },
};

static_assert (sizeof (kErProfiles) / sizeof (kErProfiles[0]) == static_cast<size_t> (ErProfile::Count),
               "one spec per ErProfile id");

/** How far each tap time may move per channel, either way. */
inline constexpr float kErJitter = 0.04f;

/** The profile a stored id runs: anything this build does not know is Off. */
inline int resolveErProfile (int stored) noexcept
{
    return (stored > 0 && stored < static_cast<int> (ErProfile::Count)) ? stored : 0;
}

/** 1 - exp(-2 pi f / sr) without libm - the reverb's tone filter's law, so a
    render of the same session hashes the same on every platform. */
inline float erOnePoleCoef (float hz, double sampleRate) noexcept
{
    const float sr = static_cast<float> (sampleRate > 0.0 ? sampleRate : 48000.0);
    const float f = hz < sr * 0.49f ? hz : sr * 0.49f;
    const float x = 6.2831853071795864f * f / sr;
    return 1.0f - spatcore::dsp::FastDecibels::exp2 (-x * 1.4426950408889634f);
}

/** One profile built for one channel at one size, in samples. */
struct ErTapSet
{
    static constexpr int kMaxTaps = 24;

    int profile = 0;                // resolved: 0 = Off, no taps and no tail delay
    float size = 1.0f;              // the quantised size it was built at
    int numFirst = 0;               // taps [0, numFirst) are first order
    int numTaps = 0;
    int delay[kMaxTaps] = {};       // samples after the direct sound
    float gain[kMaxTaps] = {};      // signed
    int tailDelay = 0;              // samples
    int maxRead = 0;                // the longest delay of all of them
    float darkCoef = 1.0f;

    bool isOn() const noexcept      { return profile != 0; }

    /** Whether this is the set (profile, size) builds. Off is Off at any size. */
    bool matches (int resolvedProfile, float quantisedSize) const noexcept
    {
        if (profile == 0 || resolvedProfile == 0)
            return profile == resolvedProfile;

        return profile == resolvedProfile && size == quantisedSize;
    }
};

/** Builds `profile` at `size` for the channel with `noiseKey`. Realtime-safe. */
inline void buildErTapSet (ErTapSet& set, int profile, float size, double sampleRate,
                           std::uint32_t noiseKey) noexcept
{
    const int p = resolveErProfile (profile);
    const ErProfileSpec& spec = kErProfiles[p];
    const double samplesPerMs = (sampleRate > 0.0 ? sampleRate : 48000.0) * 0.001;

    set.profile = p;
    set.size = size;
    set.numFirst = 0;
    set.numTaps = 0;
    set.tailDelay = static_cast<int> (static_cast<double> (spec.tailDelayMs) * size * samplesPerMs + 0.5);
    set.maxRead = set.tailDelay;
    set.darkCoef = erOnePoleCoef (spec.darkHz, sampleRate);

    // A stream of its own, apart from the one that picks the FDN's network.
    const std::uint32_t key = spatcore::dsp::FrDiffusion::makeKey (static_cast<int> (noiseKey & 0x7FFFFFFFu),
                                                                    static_cast<int> (ModuleId::Reverb) + 64);

    // First order first, then the rest; each group keeps its arrival order.
    for (int pass = 0; pass < 2; ++pass)
    {
        for (int j = 0; j < spec.numTaps && set.numTaps < ErTapSet::kMaxTaps; ++j)
        {
            const ErTapSpec& t = spec.taps[j];
            const bool first = t.order == 1;
            if (first != (pass == 0))
                continue;

            const float jitter = 1.0f + kErJitter * spatcore::dsp::FrDiffusion::hashNoiseBipolar (2u * static_cast<std::uint32_t> (j), key);
            int d = static_cast<int> (static_cast<double> (t.ms * jitter) * size * samplesPerMs + 0.5);
            if (d < 1)
                d = 1;

            float g = t.gain;
            if (! first && spatcore::dsp::FrDiffusion::hashNoiseBipolar (2u * static_cast<std::uint32_t> (j) + 1u, key) < 0.0f)
                g = -g;

            set.delay[set.numTaps] = d;
            set.gain[set.numTaps] = g;
            ++set.numTaps;
            if (first)
                ++set.numFirst;
            if (d > set.maxRead)
                set.maxRead = d;
        }
    }
}

/** The longest read any profile can make at the largest size, in samples. */
inline int erMaxReadSamples (double sampleRate) noexcept
{
    const double samplesPerMs = (sampleRate > 0.0 ? sampleRate : 48000.0) * 0.001;
    double longest = 0.0;

    for (const ErProfileSpec& spec : kErProfiles)
    {
        if (spec.tailDelayMs > longest)
            longest = spec.tailDelayMs;

        for (int j = 0; j < spec.numTaps; ++j)
        {
            const double ms = static_cast<double> (spec.taps[j].ms) * (1.0 + kErJitter);
            if (ms > longest)
                longest = ms;
        }
    }

    return static_cast<int> (longest * kReverbMaxSize * samplesPerMs) + 2;
}

} // namespace spatcore::effects
